language: cpp

compiler: gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   secure: "Fap7w3/EkoI47HTiHLIWMrQPNZzGK2x86otjoENHvHvu2/2phYDWJEnsRVqMUq9CVw9Dw/rbajbM8qp53oEI1sBqc3UowryAdshUosw5FfDsau4MJsTQrTBLRDc8pEuBux51ULlnxxP2JXdM3f/96Xi7e+PxVO/vGGCLCcmJd/8nUhZ28SXVJYQ5eAeUrNWuimI8Ba+ldFHNgQKcvFdLtyBIXFlMBYmuBqjut8+O+s7YeCvjkrhA4G0RfR62ZMo4ztCm+DqZbvFmOPCuFJOb09wcbblcYwR9kWwTWi/6NVH27gJ2hM5pq3J4j98G6CcV5TzqZFukpXypWNDPtRSjits54GTL3ZhvDIc4lWCd21Kv+NpXSZcph0iOJf3elKmu0dwHw4rgY3ySUBk7U2u6doKFfCMrQYIfHvlH1HE7h0eyIXU7ukzMW6qAuviXj6W/+tmYVI5+OTQ5R/t5AbwAheY+/4cZu2HWb0a0sNe2NY6YQGKbVHJ7p0CwSMzzgH2THsoBAyHtWvOwTkc566fzQGNUHQ1nn3nMl/qzTRxLiqCenkGoZ3FRVj4q+Yb400vA/qxhP4WUWy5QWGlzgtE5xSAKziFQfdtRWz32lsOgd2g2j3Xa5JW/TWjcR+FHL+Rlxp13VJDfYO8LCYSqGfo7zXdvO8kvLCJjPkFwpY58trk="

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-5
  - export CXX="g++-5"
  - export CC="gcc-5"

addons:
  coverity_scan:
    project:
      name: "GENIVI-Ramses/ramses"
      description: "RAMSES"
    notification_email: ramses@genivi.org
    build_command_prepend: "mkdir build; cd build; cmake .."
    build_command: "cmake --build build"
    branch_pattern: coverity_scan

script:
  - if [[ "${COVERITY_SCAN_BRANCH}" == 1 ]];
      then
        echo "Don't build on coverty_scan branch.";
        exit 0;
    fi
