language: cpp

compiler: gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "KF09o3c6cBpxPdJFDjHbkKGSKfABZNzLRurcvzfOashvScueyNjdv5zzgvV0Nb6Dix7jq/n4WPOzT2ljqimIgPPc8o4XKkq63fIQgsHWftuJjJ3lOAcorQ3qjk6V9B9nnIsRW0hU9p8fA2e0unXRnCfwPIuGD7oJ9NTZA+d/MeqieaJfB6xVkX/TM8bewvVYkDuiebC4koNK/oXFTFPs5+TNojYlUllR7/ysUkXpO0E0mQbLE/lQWfHYGUeJgqwOKfdMcJadKlQwyCY5wXTMdinglJZ4MwWkrzzXtH97vkO2z9VGy0Z5nvMA1Xbt9HmGCDcVdq2/zRGQXmLf9Dri0z0w0BcMqvkQkBKZsG4q8FcPoAneoKPSZChryJkY+RHAsl9XO5OQNthuVEh5k4afWiQij0lsmClR2Jq+ZubY3zrTLZYtCReCzu+KmWcSBvrK3+SUvnrUyH2+Q/+2zyVRmu0CFZlOZ+m6Q0IvFsb9u4SMZfr6guoJlYaVuHjEBJ9gt4SkvO4HnELg2ZTSRf5IpYQkhlnhAqWk+ge4kMzyG/eZXXNyty0CHYs9vWoy8Ms0CaIn7EZizuGLT12C8gbWZ/NslgfzXfvaCwMo4RZCq+PWb/QJBeta9zK/K+pAmT1rdE2ryXW3MEe4UL+rdn8COVf743bqhny4lTct7ng5inE="

before_install:
  - mkdir build; cd build; cmake ..

addons:
  coverity_scan:
    project:
      name: "GENIVI-Ramses/ramses"
      description: "RAMSES"
    notification_email: ramses@genivi.org
    build_command_prepend: "mkdir build; cd build; cmake .."
    build_command: "cd build; cmake --build ."
    branch_pattern: coverity_scan

script:
  - cd build; cmake --build .
